socket_base: fix 'va_list' has not been declared error
This patches tries to fix following compiler error with gcc 4.7.1/uClibc 0.9.33.2
on ARM (OpenWRT):

	In file included from device.cpp:51:0:
	socket_base.hpp:105:35: error: 'va_list' has not been declared
	make[5]: *** [libzmq_la-device.lo] Error 1

Signed-off-by: Petr Štetiar <ynezz@true.cz>